### ISSUE TITLE
Option to return `NA` or `NULL` if path is not found

### ISSUE THREAD

**Issue by dbosak01** [ArcadeAntics/this.path#1]
I’d like to request a feature for the this.path() function.  It would be nice to have a parameter to return an NA or NULL if the path is not found, instead of throwing an error.  As it stands, I have to wrap all my this.path() calls in tryCatch() in case it can’t get the path for some reason.  It would convenient to have an option to turn off the error and just let me know quietly if the path is not available.  Thanks for your consideration.

**Comment by ArcadeAntics** [comment]
I've introduced a function `this.path2` which should return `NULL` when there is no executing script.
`this.path2` may still throw errors for other reasons, I'll include a screenshot of the documentation for reference.

![image](https://user-images.githubusercontent.com/14181583/135762527-35858f72-8a70-461d-86f2-e4ab1efe8441.png)

If you'd like to request a different name for the function, I'm happy to add it!
