### ISSUE TITLE
Run script as background job in Rstudio. error

### ISSUE THREAD

**Issue by leechaowen** [ArcadeAntics/this.path#17]
Run script as background job in Rstudio. error comes out.  Could you help to fix it? Thanks.

Disabled features: fontconfig, x11
Error in .gui.path() : 
  R is running from a shell and argument 'FILE' is missing
Calls: .rs.sourceWithProgress -> eval -> eval -> this.dir -> .gui.path -> shFILE

**Comment by ArcadeAntics** [comment]
Hiya @leechaowen !


I guess I'm not as much of an RStudio expert as I thought, I've never even used background jobs before. That being said, I think I fixed it, and it should now output:

```
Source: background job in 'RStudio'
[1] "C:/Users/iris/Documents/test.R"
```

Please install the newest development version of `package:this.path`:

```
install.packages("this.path",
    repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
```

test it out and let me know if it works.

If it works, I'll close this issue once the update has been published on CRAN. If not, please show me what output or errors you receive.

Thank you!

**Comment by leechaowen** [comment]
i fail to install the development version due to network problem.  the web raw.githubusercontent.com is blocked by China gov. I think we could close this issue. 新年快乐 happy new year.

**Comment by ArcadeAntics** [comment]
Hmm, you might be able to install it like this:

```
remotes::install_github("ArcadeAntics/this.path")
```

**Comment by leechaowen** [comment]
> Hmm, you might be able to install it like this:
> 
> ```
> remotes::install_github("ArcadeAntics/this.path")
> ```

it works. Run as background job is fine. No issue. Thanks.

**Comment by ArcadeAntics** [comment]
Hiya @leechaowen !


Update 2.4.0 was published to CRAN a few hours ago, so you should be able to install it directly from there:

```
install.packages("this.path")
```

Let me know if you have any further issues!


Regards,
    Iris
