### ISSUE TITLE
`this.path()` not working when run from a shell in Ubuntu on an Android, incorrectly claims R is running in an unrecognized manner

### ISSUE THREAD

**Issue by leechaowen** [ArcadeAntics/this.path#3]
hi, run R in termux there is an error comes out  'this.path' used in an inappropriate fashion.

`root@localhost:~# cat testThisPath.R
library(this.path)
print(this.dir())

root@localhost:~# Rscript testThisPath.R
Error in .this.dir(...) : 'this.path' used in an inappropriate fashion
* no appropriate source call was found up the calling stack
* R is being run in an unrecognized manner
Calls: print -> this.dir -> .this.dir -> .this.path
Execution halted`

i install termux from f-droid then install ubuntu in termux by follow steps:

pkg update

pkg install proot

pkg install proot-distro

proot-distro install ubuntu

proot-distro login ubuntu

 compiled latest R in ubuntu.

> R.version
               _
platform       aarch64-unknown-linux-gnu
arch           aarch64
os             linux-gnu
system         aarch64, linux-gnu
status
major          4
minor          2.1
year           2022
month          06
day            23
svn rev        82513
language       R
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid

**Comment by leechaowen** [comment]
here comes my detail way compiled latest R in ubuntu. there are many ways to install ubuntu in termux. here use the  official way install ubuntu in termux by  proot-distro command.


pkg update
pkg install proot
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu

**#all below run in ubuntu**
apt-get update
apt-get install vim default-jdk wget 
apt-get install build-essential gfortran
apt-get install bzip2  libbz2-dev xz-utils zip gnupg libxml2  libreadline-dev libtiff-devapt-get install libcairo2-dev libicu-dev liblzma-dev 
apt-get install libxml2-dev libssl-dev libpng-dev
apt-get install libfontconfig1-dev libxml2-dev libxml2-dev libcurl4-openssl-dev libssl-dev


#openssl
cd ~
mkdir Downloads
cd Downloads
wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
tar -xzvf openssl-1.1.1o.tar.gz
cd openssl-1.1.1o
mkdir -p  /usr/local/openssl-1.1.1o
./config shared --prefix=/usr/local/openssl-1.1.1o
make
make install
echo "/usr/local/openssl-1.1.1o/lib" >> /etc/ld.so.conf
ldconfig -v


cd ~
cd Downloads
apt-get remove curl libcurl4
apt autoremove
wget https://github.com/curl/curl/releases/download/curl-7_83_0/curl-7.83.0.tar.gz
tar -xzvf curl-7.83.0.tar.gz
cd curl-7.83.0 
./configure  --with-wolfssl --with-openssl=/usr/local/openssl-1.1.1o
make
make install
echo "/usr/local/lib" >> /etc/ld.so.conf
ldconfig -v


cd ~
cd Downloads
wget  https://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
tar -xzvf libpng-1.6.37.tar.gz
cd libpng-1.6.37
./configure
make
make install


cd ~
cd Downloads
wget https://cran.r-project.org/src/base/R-4/R-4.2.1.tar.gz
tar -xzvf R-4.2.1.tar.gz
cd R-4.2.1
mkdir -p  /usr/local/R-4.2.1
cd doc
touch NEWS.rds
touch NEWS.2.rds
touch NEWS.3.rds
cd ..
./configure --with-x=no --enable-R-shlib --with-libpng --prefix=/usr/local/R-4.2.1
make
make install


cd ~
cp .bashrc .bashrc.bak
echo "PATH=/usr/local/R-4.2.1/bin:$PATH" >> .bashrc

source .bashrc

**Comment by leechaowen** [comment]
here comes my detail way compiled latest R in ubuntu. there are many ways to install ubuntu in termux. here use the  official way install ubuntu in termux by  proot-distro command.


pkg update
pkg install proot
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu

**#all below run in ubuntu**
apt-get update
apt-get install vim default-jdk wget 
apt-get install build-essential gfortran
apt-get install bzip2  libbz2-dev xz-utils zip gnupg libxml2  libreadline-dev libtiff-devapt-get install libcairo2-dev libicu-dev liblzma-dev 
apt-get install libxml2-dev libssl-dev libpng-dev
apt-get install libfontconfig1-dev libxml2-dev libxml2-dev libcurl4-openssl-dev libssl-dev


#openssl
cd ~
mkdir Downloads
cd Downloads
wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
tar -xzvf openssl-1.1.1o.tar.gz
cd openssl-1.1.1o
mkdir -p  /usr/local/openssl-1.1.1o
./config shared --prefix=/usr/local/openssl-1.1.1o
make
make install
echo "/usr/local/openssl-1.1.1o/lib" >> /etc/ld.so.conf
ldconfig -v


cd ~
cd Downloads
apt-get remove curl libcurl4
apt autoremove
wget https://github.com/curl/curl/releases/download/curl-7_83_0/curl-7.83.0.tar.gz
tar -xzvf curl-7.83.0.tar.gz
cd curl-7.83.0 
./configure  --with-wolfssl --with-openssl=/usr/local/openssl-1.1.1o
make
make install
echo "/usr/local/lib" >> /etc/ld.so.conf
ldconfig -v


cd ~
cd Downloads
wget  https://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
tar -xzvf libpng-1.6.37.tar.gz
cd libpng-1.6.37
./configure
make
make install


cd ~
cd Downloads
wget https://cran.r-project.org/src/base/R-4/R-4.2.1.tar.gz
tar -xzvf R-4.2.1.tar.gz
cd R-4.2.1
mkdir -p  /usr/local/R-4.2.1
cd doc
touch NEWS.rds
touch NEWS.2.rds
touch NEWS.3.rds
cd ..
./configure --with-x=no --enable-R-shlib --with-libpng --prefix=/usr/local/R-4.2.1
make
make install


cd ~
cp .bashrc .bashrc.bak
echo "PATH=/usr/local/R-4.2.1/bin:$PATH" >> .bashrc

source .bashrc

**Comment by ArcadeAntics** [comment]
Would you mind running the following for me in your R session?

print(.Platform)
print(sessionInfo())

I think this debug information might help me figure out the issue.

Also, would you mind re-running your script like this:

library(this.path)
assignInNamespace("os.unix", TRUE, "this.path")
assignInNamespace("os.unix.gui.x11", TRUE, "this.path")
assignInNamespace("in.shell", TRUE, "this.path")
print(this.dir(verbose = TRUE))

If that seems to generate the expected output, then it should be an easy fix and I could publish a fix very quickly.

Also, very important thing. If you've installed "this.path" in the last day or so, you've probably installed version 1.0.0. Please do not use this version, I'm experiencing issues with it. You should either install version 0.11.0 or 1.0.1 (though I have not finished confirming that 1.0.1 fixes the issue). You could install either like this in your R session:

install.packages("https://raw.githubusercontent.com/ArcadeAntics/PACKAGES/src/contrib/Archive/this.path/this.path_0.11.0.tar.gz")

or

install.packages("https://raw.githubusercontent.com/ArcadeAntics/PACKAGES/src/contrib/this.path_1.0.1.tar.gz")

**Comment by leechaowen** [comment]
i remove the old version and install follow your way , test one by one  all  both could print  current path with your code.
but  still error without assignInNamespace like your codes.

> .Platform
$OS.type
[1] "unix"

$file.sep
[1] "/"

$dynlib.ext
[1] ".so"

$GUI
[1] "unknown"

$endian
[1] "little"

$pkgType
[1] "source"

$path.sep
[1] ":"

$r_arch
[1] ""

> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/local/R-4.2.0/lib/R/lib/libRblas.so
LAPACK: /usr/local/R-4.2.0/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.1



root@localhost:~/TestCode# pwd
/root/TestCode

root@localhost:~/TestCode# cat TestCode.R
library(this.path)
assignInNamespace("os.unix", TRUE, "this.path")
assignInNamespace("os.unix.gui.x11", TRUE, "this.path")
assignInNamespace("in.shell", TRUE, "this.path")
print(this.dir(verbose = TRUE))

root@localhost:~/TestCode# Rscript TestCode.R
Source: shell argument 'FILE'
[1] "/root/TestCode"

**Comment by ArcadeAntics** [comment]
I believe I've fixed the issue. Basically, I was using something like `.Platform$OS.type == "unix" && .Platform$GUI == "X11"`  to test if we were running from a shell on a unix-alike, but clearly that doesn't work for certain scenarios like yours. I've made a fix, called it version 1.0.2, and you can install it with:

install.packages("this.path", repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")

I won't be able to publish this update on CRAN for a month or so, the CRAN devs don't like people publishing updates more frequently than that.

Can you let me know if this fixes the issue?

**Comment by leechaowen** [comment]
Thanks.it's fixed now.


> remove.packages("this.path")
Removing package from ‘/usr/local/R-4.2.0/lib/R/library’
(as ‘lib’ is unspecified)
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
> install.packages("this.path", repos = "https://raw.githubusercontent.com/ArcadeAntics/PACKAGES")
trying URL 'https://raw.githubusercontent.com/ArcadeAntics/PACKAGES/src/contrib/this.path_1.0.2.tar.gz'
Content type 'application/octet-stream' length 57577 bytes (56 KB)
==================================================
downloaded 56 KB

* installing *source* package ‘this.path’ ...
** using staged installation
** libs
gcc -I"/usr/local/R-4.2.0/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c basename2.c -o basename2.o
gcc -I"/usr/local/R-4.2.0/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
gcc -I"/usr/local/R-4.2.0/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c pathjoin.c -o pathjoin.o
gcc -shared -L/usr/local/R-4.2.0/lib/R/lib -L/usr/local/lib -o this.path.so basename2.o init.o pathjoin.o -L/usr/local/R-4.2.0/lib/R/lib -lR
installing to /usr/local/R-4.2.0/lib/R/library/00LOCK-this.path/00new/this.path/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (this.path)

The downloaded source packages are in
        ‘/tmp/RtmpXCEheM/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
>
>
>
>
> q()
Save workspace image? [y/n/c]: n

root@localhost:~/TestCode# Rscript testThisPath.R
[1] "/root/TestCode"

root@localhost:~/TestCode# cat testThisPath.R
library(this.path)
print(this.dir())
