### ISSUE TITLE
`this.path()` not working in Jupyter

### ISSUE THREAD

**Issue by leechaowen** [ArcadeAntics/this.path#5]
i install latest version 1.0.2-57 .i want to using this.path in jupyter. but meet issue.

Error in .this.path(verbose = FALSE): 'this.path' used in an inappropriate fashion
* no appropriate source call was found up the calling stack
* R is being run from a shell and argument 'FILE' is missing
Traceback:

1. this.dir()
2. .this.dir(verbose)
3. .this.path(verbose = FALSE)
4. shFILE(original, default = {
 .     stop(thisPathNotExistsError("'this.path' used in an inappropriate fashion\n", 
 .         "* no appropriate source call was found up the calling stack\n", 
 .         "* R is being run from a shell and argument 'FILE' is missing"))
 . })

using here is fine. but i do not want using here. any solutions ?

![image](https://user-images.githubusercontent.com/44858442/195243430-de35a491-05e5-4aa5-b866-961c832a216a.png)

**Comment by ArcadeAntics** [comment]
As far as I've tested, `here::here()` is not doing any better than `this.path::this.dir()`. `here::here()` cannot find a directory meeting any of the criteria, you should be able to see this for yourself by running:

```
here::dr_here()
```

For me, this looks something like:

![image](https://user-images.githubusercontent.com/14181583/195522060-4f8e0d95-38b1-4e3f-a48f-6a371299e763.png)

inside your notebook. I've added `initwd` and `getinitwd()` to `this.path_1.0.2-62` which means you could change `this.dir()` to something like:

```
this.dir(default = initwd)
# or this.dir(default = getinitwd())
```

and then theoretically it would behave the same as `here`. Unfortunately, I don't have a fix for this. I tried looking at package `IRkernel` but it doesn't seem to have any functionality for retrieving the path of the open document. There's some hack-ish shit that someone made for use in python, so I'll try to look into making something similar for R. As of now, I don't have a real solution, sorry :(

**Comment by leechaowen** [comment]
I remove and install  the latest version . i think it's ok now after add the parameters like yours. Thanks.

**Comment by ArcadeAntics** [comment]
I'm hoping to revisit this issue, I don't like the current implementation. It's fine, but it could really be better. I should have a tarball available by the end of the week that will fix this.

**Comment by ArcadeAntics** [comment]
I came up with a solution, which is to list the files in the initial working directory, select the ipynb files, and read their contents for an expression matching the top-level expression. This is not a pretty solution, it's full of time-consuming guess-work, but it seems to do the job. It's the best I can do unless the developers of Jupyter / / IRkernel specifically add a function for retrieving the path.
