### ISSUE TITLE
`this.path()` not working in RStudio, incorrectly claims R is running from a shell

### ISSUE THREAD

**Issue by leechaowen** [ArcadeAntics/this.path#8]
Bad news, I install the latest Rstudio this morning there is some errors comes out when running  rmd files. Before update everything is OK.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/44858442/210121699-c70408c4-cda3-4ca8-82b7-7481ab54eeb0.png">

Error in .this.path(verbose = FALSE) : 
  'this.path' used in an inappropriate fashion
* no appropriate source call was found up the calling stack
* R is being run from a shell and argument 'FILE' is missing
Calls: <Anonymous> ... eval -> eval -> here -> .this.path -> normalized.shFILE

**Comment by leechaowen** [comment]
i reinstall all packages i need ,it fix now. may be  broken the dependency after update the Rstudio

**Comment by ArcadeAntics** [comment]
I'm glad to see it's working again! I suggest upgrading to the most recent version, 1.2.0:

```R
update.packages(oldPkgs = "this.path")
```

It has some fixes to better determine if R is running from RStudio. Thank you for your continued usage and support of my R package!
